//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: prosthesis.proto
namespace prosthesis
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandshakeRequest")]
  public partial class HandshakeRequest : global::ProtoBuf.IExtensible
  {
    public HandshakeRequest() {}
    
    private string _versionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"versionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string versionId
    {
      get { return _versionId; }
      set { _versionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandshakeResponse")]
  public partial class HandshakeResponse : global::ProtoBuf.IExtensible
  {
    public HandshakeResponse() {}
    
    private int _commandPort;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"commandPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int commandPort
    {
      get { return _commandPort; }
      set { _commandPort = value; }
    }
    private string _versionId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"versionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string versionId
    {
      get { return _versionId; }
      set { _versionId = value; }
    }
    private bool _validConnection;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"validConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool validConnection
    {
      get { return _validConnection; }
      set { _validConnection = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProsthesisHeartbeat")]
  public partial class ProsthesisHeartbeat : global::ProtoBuf.IExtensible
  {
    public ProsthesisHeartbeat() {}
    
    private int _ts;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ts
    {
      get { return _ts; }
      set { _ts = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}